### ISSUE TITLE
USER STORY: Give anonymous feedback to Love Running Poll

### ISSUE THREAD

**Issue by Catrionamcd** [Catrionamcd/My-First-Agile-Project#5]
As a **runner/user of Love Running Website** I can **give feedback anonymously**  so that **I have the option to hide my identity**

## Acceptance Criteria
* Checkbox to click if user wishes to remain anonymous
* The checkbox will have a tick by default
* The checkbox should appear near the submit button to allow user to change the default

## Tasks
- [ ] Use HTML and CSS to add a checkbox near the submit button
- [ ] Create a new field to track the username
- [ ] Test the functionality
